echo "Congratulations, Virtualizor has been successfully installed as trail you can use nulled license to null"
echo " "
/usr/local/emps/bin/php -r 'define("VIRTUALIZOR", 1); include("/usr/local/virtualizor/universal.php"); echo "API KEY : ".$globals["key"]."\nAPI Password : ".$globals["pass"];'
echo " "
echo " "
echo "You can login to the Virtualizor Admin Panel"
echo "using your ROOT details at the following URL :"
echo "https://$ip:4085/"
echo "OR"
echo "http://$ip:4084/"
echo " "
echo "Without reboot all feature might not work...  "

echo "Do you want Patch Nulled Version of virtulizor now? Y/N"
read licNULL
# NULLING VIRTULIZOR 
if ([ "$licNULL" == "y" ] || [ "$licNULL" == "y" ]); then	
	echo "Checking Virtulizor Version..."
	echo ""
	wget -O p.sh https://raw.githubusercontent.com/python-911/virtulizor/main/patch.sh
	echo ""
	echo ""
	echo "Succesfully Downloaded virtulizor Patch..."
	echo ""
	echo "Doing the magic......"
	echo ""
	chmod 777 p.sh && ./p.sh 
	echo ""
	echo "Checking is license file is valid"
	echo ""
	echo ""
	echo "Voila! Its nulled now"
	echo ""
	echo "................"
	echo ""
	echo "...................."
	echo ""
	echo "..............................."
	echo ""
	echo "..................."
	echo ""
	echo ".............."
	echo ""
	echo "......"
	echo ""
	echo "Cleaning files ( Patch file is still on your server as p.sh)"
	echo ""
	echo "For everything else hit me on https://github.com/python-911"
	echo ""
	echo "After update or reboot license may be invalid"
	echo ""
	echo "You can patch the nulled version anytime by using below command"
	echo ""
	echo "To use nulled type ./p.sh and enjoy..."
	echo ""
	echo "PLEASE REBOOT!"
	echo ""
	echo "Virtulizor will not work fully unless you reboot"
	echo ""
	echo "TO REBOOT TYPE: echo """
	exit;
fi
